[env:uno]
platform = atmelavr@^5.1.0
framework = arduino
board = uno
lib_deps = 
	paulstoffregen/PWMServo@2.1.0
	arduino-libraries/Ethernet@2.0.2

build_unflags = -fpermissive
build_flags = -Wall -Wextra
